### ISSUE TITLE
GPU support

### ISSUE THREAD

**Issue by Gegam** [pvnieo/Low-light-Image-Enhancement#3]
Does the model run on a GPU? If not, how can this be done? And are multiple GPUs supported?

I also noticed that images larger than 1000px are skipped due to lack of memory. I get pretty slow performance on RTX3080

**Comment by pvnieo** [comment]
Hi,

* The actual implementation doesn't run on the gpu, so even if you have a RTX3080, it won't be used.
* Bigger images are skipped because the optimization will take too much time, but you could not skip them and wait for the optimization to converge!
* I don't see why you need multiple gpus for this problem
* I you want to use gpu, you can convert this implementation to your favorite deep learning framework (e.g pytorch, tensorflow), and for that, you need to re-implement all the predefined functions available in OpenCV, like sobel filter and Mertens merge.

Hope this answer your question!
